# Site settings
title: Custom Phone Case Studios
email: customscases@cpcs.ca
url: https://example.github.io
description: Express yourself with original phone cases and designs made by you. Customize any phone case model so you can personalize and protect any of your devices. Explore the possibilities and make it yours.
meta_author: Shechtman Noah Shariff Haikal

# Build settings
markdown: kramdown
permalink: pretty
